name: Hello world

on:
  push: 
    branches:
      - main
    
jobs:
  echo_hello_world:
    runs-on: windows-latest
    steps:
      - name: Printar hello world
        run: echo hello world
      - name: Printar hello people
        run: echo hello people
