name: Hello world

on:
  push: 
    branches:
      - main
  workflow_dispatch:
  
jobs:
  echo_hello_world:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Printar hello world
        run: echo hello world
      - name: Printar hello people
        run: echo hello people
